common:
  hypotheses: ${HYP_DIR}/${SUBSET}.tgt.${decoding_hyp}.${NUM_hyp}
  num_candidates: ${NUM_hyp}
  num_references: ${NUM_ref}
  nbest: 1
  source: ${DATA_DIR}/${SUBSET}.src
  references: ${REF_DIR}/${SUBSET}.tgt.${decoding_ref}.${NUM_ref}
  format: plain
  output: ${DIR}/${SUBSET}.tgt.${METRICS}-${DECODING}.${decoding_hyp}.${NUM_hyp}-${decoding_ref}.${NUM_ref}
  report: ${DIR}/${SUBSET}.tgt.${METRICS}-${DECODING}.${decoding_hyp}.${NUM_hyp}-${decoding_ref}.${NUM_ref}.logs
  report_format: tsv
  decoder: ${DECODING}
  metric: ${METRIC_TYPE}
